branches:
  only:
    - master
    - /^greenkeeper/.*$/

dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install Pygments
cache: pip

script:
  - pushd mmtpygments/test && python test.py https://comfreek.github.io/mmt-pygments-lexer/mmtpygments/test/ && popd

before_deploy:
  # Prevent auxiliary and other compilation artifacts from the MMT Git submodule archives to be pushed to gh-pages
  # We just want the rendered .mmt.html output files
  - find mmtpygments/test/data -type f ! -name '*.mmt.html' -delete

  # This .gitignore ignores the very .mmt.html output files, hence delete it before deployment to gh-pages
  - rm mmtpygments/test/.gitignore

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_PAGES_DEPLOYMENT_TOKEN
  keep-history: false
  on:
    branch: master
  target-branch: gh-pages
