branches:
  only:
    - master
    - /^greenkeeper/.*$/

dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install Pygments
cache: pip

script:
  - cd test && python test.py https://comfreek.github.io/mmt-pygments-lexer/test/

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_PAGES_DEPLOYMENT_TOKEN
  keep-history: true
  on:
    branch: master
  target-branch: gh-pages
