branches:
  only:
    - master
    - /^greenkeeper/.*$/

dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install Pygments
cache: pip

script:
  - pushd mmtpygments/test && python test.py https://comfreek.github.io/mmt-pygments-lexer/mmtpygments/test/ && popd

before_deploy:
  # So that our render results, which are ignored by this very .gitignore, are actually published
  # to gh-pages.
  - rm mmtpygments/test/.gitignore

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_PAGES_DEPLOYMENT_TOKEN
  keep-history: false
  on:
    branch: master
  target-branch: gh-pages
