branches:
  only:
    - master
    - /^greenkeeper/.*$/

os: linux
dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install pipenv
  - pipenv install
cache: pip

script:
  - pushd mmtpygments/test && pipenv run python test.py https://comfreek.github.io/mmtpygments/mmtpygments/test/ && popd

before_deploy:
  # Prevent auxiliary and other compilation artifacts from the MMT Git submodule archives to be pushed to gh-pages
  # We just want the rendered .mmt.html output files
  - find mmtpygments/test/data -type f ! -name '*.mmt.html' -delete

  # This .gitignore ignores the very .mmt.html output files, hence delete it before deployment to gh-pages
  - rm mmtpygments/test/.gitignore

deploy:
  - provider: pages
    github_token: $GITHUB_PAGES_DEPLOYMENT_TOKEN
    on:
      branch: master
    target_branch: gh-pages

  - provider: pypi
    # Deploy to PyPI from tagged commits 
    # See https://docs.travis-ci.com/user/deployment/pypi/,
    # https://stackoverflow.com/questions/30156581/travis-ci-skipping-deployment-although-commit-is-tagged
    on:
      all_branches: true
      tags: true
      skip_existing: true
    user: "__token__"
    password:
      secure: "DeNZhB8TZ4wQzKk87yWqijz7NW790r+oIX8gOPMyncPTDbtUetlktQKUKXJB3aQVJDkDyLJwIUqZEz0NGDRBcLakWnT1METXBLtPoHf8mXfcs6J40toS7yztnhhNgQqrykntlUWXCqMDgHMUiVdfEtJGb07rpM8iYvw2FCxXHVFapTVswjwOr9jB3D7/HM0hWWemn+BLa11BnUZ8UMjsLomd32khd3zfKMo2b6pB++Dv9A7B9rnBi0PJGhTejfTKlauo3Cd4QXcdzlF0vRp4AjOvOXzXBH6BlLeKl8mblmYGACfCUelK+mgwryTLl2GSwP2QQaBf6J8ZOh2wmk8sb50uZXLcoYQiIcJFVfB2ePPlnCvKPtQihVHw7dLsGg4EOpB0IWJ2plvYZ6rvMiKiNw6EgPQtU11H+wISFsQ9Lk0q75IJERcBMYUDbycfa6PlFyGBxfY7bKeXlfOvpzxl+lqKciAxZkk1p6LotWpuW2fs94eAX+3U752me+z3TP7/QkJrvh7onmhBFHTVaqmaHSBpuVq3nNa7/pkmY3Le56mI9vv1hGEk3mx2QcJxECcubRfcZ11i/6TuDkgRz1/YGqCzLzqu91650gjNmfhGRj3Zt1oJK/w+ZMDwgFHGOCDKPREFNoivA5hLqk5k9wQ8ahEmU2DPvlph+xua3LNXUlc="
